---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Gather package facts
    package_facts:
      manager: auto
  - name: Ensure Nginx is existed
    assert:
      that:
        - '"nginx" in ansible_facts.packages'
  - name: Debug if package is present
    debug:
      msg: 'yes, nginx is present'
    when: '"nginx" in ansible_facts.packages'
