---
- hosts: all
  gather_facts: true
  any_errors_fatal: true
  tasks:
  - name: Install dependencies for Ubuntu
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'dirmngr']
      update_cache: true
      state: present
    when: ansible_facts['os_family']=="Debian"
  - name: (Debian/Ubuntu) Add NGINX signing key
    apt_key:
      id: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
      url: "https://nginx.org/keys/nginx_signing.key"
    when: ansible_facts['os_family'] == "Debian"
  - name: Install NGINX from package
    package:
      name: nginx
      state: present
      use: auto
  - name: Gather package facts
    package_facts:
      manager: auto
  - name: Debug if package is present
    debug:
      msg: 'yes, nginx is present'
    when: '"nginx" in ansible_facts.packages'
